### ISSUE TITLE
Replacing this with a PWA

### ISSUE THREAD

**Issue by BradKML** [negue/HabitRPG-Metro#25]
As observed in these news articles, there is a one-click way of converting web apps to native apps. This could be a replacement for HabitRPG-Metro using https://github.com/HabitRPG/habitica
- https://chromeunboxed.com/chrome-73-mac-os-pwa-support-all-desktops/
- https://www.amitmerchant.com/chrome73-supports-installing-pwa-native-app-macos/
- https://developer.chrome.com/blog/new-in-chrome-73/

Unfortunately, it seems that Habitica proper doesn't allow for Issues to be made on GitHub, so I have decided to make a note here.

**Comment by negue** [comment]
Hey,

this old & to be archived repo was for my native UWP / Windows Metro App for Habitica, it was built when Windows itself was pushing their Hardware for Tablets and Phone, but since they stopped developing these it also removed the "air" of me developing this app.

Now days the tablets should be able to use the website "just fine". Since Windows dropped their phones development  and support this app also got obsolete.

> doesn't allow for Issue to be made on GitHub

what do you mean? you can just open a new issue on https://github.com/HabitRPG/habitica/issues/new

or do mean because of https://github.com/HabitRPG/habitica/issues/9832 ?

As for me converting Habitica as a PWA I definitely don't have the time do that, even if the website is "converted" to a PWA it doesn't mean it'll "just" work offline and all other features (which probably takes most of the time^^)



Habitica also has native [Android](https://github.com/HabitRPG/habitica-android) and [iOS](https://github.com/HabitRPG/habitica-ios) apps, so for these platforms there is no need to convert the website to a PWA anymore.

**Comment by BradKML** [comment]
@negue judging from the looks of it, it seems they are not accepting feature requests in GitHub issues.

**Comment by negue** [comment]
Oh thats what you mean.. hmm then I guess this is the right way then

Its the footer link of "Request a Feature":
https://docs.google.com/forms/d/e/1FAIpQLScPhrwq_7P1C6PTrI3lbvTsvqGyTNnGzp1ugi1Ml0PFee_p5g/viewform

**Comment by BradKML** [comment]
Another issue I can see, is that Habitica notifications don't go through the browser PWA... which is a bit unfortunate since this is what make HabitRPG-metro good.

**Comment by negue** [comment]
Oh yeah - Browser Notifications while being outside of the Page - might be also a nice idea.

I'd suggest you use the official way :) 

either Issues on  https://github.com/HabitRPG/habitica/issues/new  or the `Request a Feature` Link in the Footer
